improved sitelist.csv manipulation with backup and tmp file, still sucks

diff --git a/server/scripts/proc/rmg b/server/scripts/proc/rmg
--- a/server/scripts/proc/rmg
+++ b/server/scripts/proc/rmg
@@ -262,12 +262,35 @@ esac
   ## Run task at each site ##
 
 SITELIST=$RMG_SERVER_METADATA_DIR/sitelist.csv
-
+SITELISTBACKUP=$RMG_SERVER_METADATA_DIR/sitelist.csv~
 if [ ! -e $SITELIST ]; 
 then
   echo "error: site configuration information not available (no sitelist.csv)." 1>&2
-  exit 1
+  if [ -e $SITELISTBACKUP ];
+  then
+    echo "error: recovering from backup" 1>&2
+    cp -f $SITELISTBACKUP $SITELIST
+  else
+    exit 1
+  fi
 fi 
+
+#check sitelist validity
+rmg_csv -l < $SITELIST > /dev/null
+if [ $? -ne 0 ];
+then
+  echo "error: sitelist is invalid" 1>&2
+  #check sitelistbackup validity
+  rmg_csv -l < $SITELISTBACKUP > /dev/null
+  if [ $? -ne 0 ];
+  then
+    echo "error: backup is unrecoverable" 1>&2
+    exit 1
+  else
+    echo "error: recovering from backup" 1>&2
+    cp -f $SITELISTBACKUP $SITELIST
+  fi
+fi
 
 SITES=$@
 if [[ "$SITES" = "all" ]]
@@ -281,9 +304,9 @@ then
   do
     if [[ "$TASK" = "auto_on" ]]
     then
-      rmg_csv $SITE auto auto < $SITELIST > tmp.csv && mv -f -b tmp.csv $SITELIST
+      rmg_csv $SITE auto auto < $SITELIST > /tmp/tmp_sitelist.csv && mv -f -b /tmp/tmp_sitelist.csv $SITELIST
     else
-      rmg_csv $SITE auto off < $SITELIST > tmp.csv && mv -f -b tmp.csv $SITELIST
+      rmg_csv $SITE auto off < $SITELIST > /tmp/tmp_sitelist.csv && mv -f -b /tmp/tmp_sitelist.csv $SITELIST
     fi
   done
   exit 0
@@ -359,7 +382,7 @@ do
       echo "$TASK $SITE"
       if [[ "$ping_computer" == "success" ]]
         then 
-          rmg_csv $SITE state $TASK < $SITELIST > tmp.csv && mv -f -b tmp.csv $SITELIST
+          rmg_csv $SITE state $TASK < $SITELIST > /tmp/tmp_sitelist.csv && mv -f -b /tmp/tmp_sitelist.csv $SITELIST
           do_update $SITE
         else 
           echo "error: couldn't update; Computer ping test wasn't successful" 1>&2
@@ -375,7 +398,7 @@ do
               echo "Powertype is nil; setting site to up instead of down"
               TASK=up
           fi
-          rmg_csv $SITE state $TASK < $SITELIST > tmp.csv && mv -f -b tmp.csv $SITELIST
+          rmg_csv $SITE state $TASK < $SITELIST > /tmp/tmp_sitelist.csv && mv -f -b /tmp/tmp_sitelist.csv $SITELIST
           do_update $SITE
           TASK=down
         else
@@ -390,10 +413,10 @@ do
           if [[ "$powertype" == "nil" ]]
             then
               echo "Powertype is nil; setting site to up instead of down"
-              rmg_csv $SITE state up < $SITELIST > tmp.csv && mv -f -b tmp.csv $SITELIST
+              rmg_csv $SITE state up < $SITELIST > /tmp/tmp_sitelist.csv && mv -f -b /tmp/tmp_sitelist.csv $SITELIST
               do_update $SITE
           fi
-          rmg_csv $SITE state down < $SITELIST > tmp.csv && mv -f -b tmp.csv $SITELIST
+          rmg_csv $SITE state down < $SITELIST > /tmp/tmp_sitelist.csv && mv -f -b /tmp/tmp_sitelist.csv $SITELIST
           do_update $SITE
           mkdir -p $RMG_SERVER_DET_DIR/$SITE 
           touch $RMG_SERVER_DET_DIR/$SITE/fetching.site
@@ -420,7 +443,7 @@ do
       echo "start $SITE"
       if [[ "$ping_computer" == "success" ]]
         then 
-          rmg_csv $SITE state active < $SITELIST > tmp.csv && mv -f -b tmp.csv $SITELIST
+          rmg_csv $SITE state active < $SITELIST > /tmp/tmp_sitelist.csv && mv -f -b /tmp/tmp_sitelist.csv $SITELIST
           do_update $SITE
         else 
           echo "error: couldn't update; Computer ping test wasn't successful" 1>&2
@@ -431,7 +454,7 @@ do
       echo "stop $SITE"
       if [[ "$ping_computer" == "success" ]]
         then
-          rmg_csv $SITE state up < $SITELIST > tmp.csv && mv -f -b tmp.csv $SITELIST
+          rmg_csv $SITE state up < $SITELIST > /tmp/tmp_sitelist.csv && mv -f -b /tmp/tmp_sitelist.csv $SITELIST
           do_update $SITE
         else 
           echo "error: couldn't update; Computer ping test wasn't successful" 1>&2
