update position to make a denser search, separate covariance calculation for more readable code

diff --git a/build_qraat b/build_qraat
--- a/build_qraat
+++ b/build_qraat
@@ -64,36 +64,40 @@ function sudocheck {
   if [ $SUDOASKED = false ]
   then
     echo Sudo privileges are required 
-    echo -n Do you have sudo privileges'?'
-    read ans
-    case $ans in
-      y|yes|YES|Y)
-        echo Continuing with script
+    #echo -n Do you have sudo privileges'?'
+    #read ans
+    #case $ans in
+    #  y|yes|YES|Y)
+    case `groups | grep sudo` in
+      '')
+        echo User is not in sudo group
+        echo Exiting. Please ensure that you have sudo privileges 
+        echo on this system to continue install. 
+        exit
+        ;;
+      *)
+        #echo Continuing with script
         SUDOASKED=true
-        sudo grep timestamp_timeout /etc/sudoers >tmp$$
-        timeout=`cat tmp$$|awk '/./ {print $4}'`
-        rm -f tmp$$
-        if [ "@@" = "@$timeout@" ]
-        then
-          sudo cp /etc/sudoers tmp$$
-          sudo chown $USER tmp$$
-          sudo chmod 644 tmp$$
-          echo "Defaults  timestamp_timeout = 90" >>tmp$$
-          sudo cp tmp$$ /etc/sudoers
-          sudo chown root /etc/sudoers
-          sudo chmod 440 /etc/sudoers
-        elif [ $timeout -lt 90 ]
-          then
-          echo You need to have a timestamp_timout in /etc/sudoers 
-          echo of 90 or more echo Please ensure that your 
-          echo timestamp_timeout is 90 or more
-          exit
-        fi
-      ;;
-    *)
-      echo Exiting. Please ensure that you have sudo privileges 
-      echo on this system to continue install. 
-      exit
+        sudo -v
+        #sudo grep timestamp_timeout /etc/sudoers >tmp$$
+        #timeout=`cat tmp$$|awk '/./ {print $4}'`
+        #rm -f tmp$$
+        #if [ "@@" = "@$timeout@" ]
+        #then
+        #  sudo cp /etc/sudoers tmp$$
+        #  sudo chown $USER tmp$$
+        #  sudo chmod 644 tmp$$
+        #  echo "Defaults  timestamp_timeout = 90" >>tmp$$
+        #  sudo cp tmp$$ /etc/sudoers
+        #  sudo chown root /etc/sudoers
+        #  sudo chmod 440 /etc/sudoers
+        #elif [ $timeout -lt 90 ]
+        #  then
+        #  echo You need to have a timestamp_timout in /etc/sudoers 
+        #  echo of 90 or more echo Please ensure that your 
+        #  echo timestamp_timeout is 90 or more
+        #  exit
+        #fi
       ;;
     esac
   fi
@@ -116,7 +120,7 @@ function node_install {
   sudocheck
   echo
   echo -n ' Installing Node software .'
-  echo `date` > $LOG
+  my_echo `date`
 
   mkdir $RMG_NODE_BUILD &> /dev/null; cd $RMG_NODE_BUILD
   my_echo "--------------------------------"
@@ -222,13 +226,24 @@ function server_install {
   fi
   echo -n '.'
   sudo ldconfig
+  echo ' done.'
+  echo
+}
 
+function db_install {
+  echo
+  echo -n 'Setting up the qraat database .'
+  my_echo `date`
   my_echo "--------------------------------"
   my_echo "Setting up the qraat database"
-  my_echo "Input the password for mysql's root account: "
+  echo "Input the password for mysql's root account: "
   read pswd 
-  mysql -u root --password=$pswd qraat < $RMG_SERVER_SRC/etc/db_schema.sql
-
+  mysql -u root --password=$pswd qraat < $RMG_SERVER_SRC/etc/db_schema.sql >>$LOG 2>&1
+  if [ ! $? = 0 ]; then
+    echo
+    echo "error: mysql: exited with error status. Check out log file for details."
+    exit $?
+  fi
   echo ' done.'
   echo 
 }
@@ -237,7 +252,7 @@ function base_install {
   sudocheck
   echo
   echo -n ' Installing Base software .'
-  echo `date` > $LOG
+  my_echo `date`
 
   mkdir $RMG_BASE_BUILD &> /dev/null; cd $RMG_BASE_BUILD
   my_echo "--------------------------------"
@@ -284,7 +299,7 @@ function base_install {
 function dist {
   echo
   echo -n ' Distributing RMG .'
-  echo `date` > $LOG
+  my_echo `date`
 
   mkdir $1 &> /dev/null; cd $1
   my_echo "--------------------------------"
@@ -322,7 +337,7 @@ function uninstall {
   sudocheck
   echo 
   echo -n ' Uninstalling RMG. '
-  echo `date` > $LOG
+  my_echo `date`
 
   cd $1
   my_echo "--------------------------------"
@@ -350,12 +365,15 @@ do
         server)
           BUILD_SECTIONS="base server"
           ;;
+        db)
+          BUILD_SECTIONS="db"
+          ;;
         all)
           BUILD_SECTIONS="base server node"
           ;;
         *)
           echo "Unrecognized section to build"
-          echo "Please specify [base, node, server, all] after install"
+          echo "Please specify [base, node, server, db, all] after install"
           exit
           ;;
       esac
@@ -469,6 +487,7 @@ if [ $INSTALL = true ]; then
       base) base_install ;;
       server) server_install ;;
       node) node_install ;;
+      db) db_install ;;
     esac
   done
 fi
