Implemented `rmg exporttx`.
Reads txlist from database and writes tx.csv.

diff --git a/serv/rmg b/serv/rmg
--- a/serv/rmg
+++ b/serv/rmg
@@ -108,6 +108,10 @@ usage: rmg task [-options] {sites}/all
 
     fetch        Download pulse data from site to server. Delete downloaded 
                  data from remote machine. 
+
+    exporttx --file FILE    Export transmitter list from the database 
+                            to a CSV file. Defaults to 'tx.csv.' in 
+                            working directory. 
     
     updatetx --file FILE    Update transmitter file on remote computer. 
                             Defaults to 'tx.csv' in working directory.
@@ -118,60 +122,10 @@ usage: rmg task [-options] {sites}/all
 !EOF!
 }
 
-  ## Get task and options ##
-
-TASK=$1 
-shift
-
-if [ ! $TASK ]
-then
-  help
-  exit 0
-fi
-
-case $TASK in
- -h|--help|help)
-   help
-   exit 0
-  ;; 
-
-  updatetx)
-    if [[ "$1" == "-f" ]] || [[ "$1" == "--file" ]] 
-    then
-      TX_FILE=$2
-      shift
-      shift
-    else     
-      TX_FILE="tx.csv"
-    fi
-    if [ ! -e $TX_FILE ]
-      then 
-        echo "error: '$TX_FILE' doesn't exist" 1>&2
-        exit 1
-    fi
-  ;;
-
-  status|update|on|off|up|down|start|stop|fetch|cyclerx|do_nothing|die|down_now)
-  ;; 
-    
-  *)
-    echo error: unrecognized task \'$TASK\'
-    exit 1
-  ;;
-
-esac 
 
   ## Set up environment ##
 PATH="/usr/local/bin:$PATH"
 source rmg_env  # setup RMG environment variables
-
-SITELIST=$RMG_SERVER_METADATA_DIR/sitelist.csv
-
-if [ ! -e $SITELIST ]; 
-then
-  echo "error: site configuration information not available (no sitelist.csv)." 1>&2
-  exit 1
-fi 
 
 
   ## Routines ##
@@ -242,8 +196,86 @@ function do_update() {
   ssh $SITE "cat > site.csv; rmg-node check"  
 
 }
+  
+function export_txlist() {
+python -c "
+import qraat, MySQLdb as mdb
+db_config = qraat.csv('$HOME/.qraat/db_auth').get(view='reader')
+db_con = mdb.connect(db_config.host, db_config.user,
+                     db_config.password, db_config.name)
+txlist = qraat.csv(db_con=db_con, db_table='txlist')
+txlist.write('$TX_FILE', exclude=['start', 'stop', 'programid', 
+                                  'alias', 'serial', 'model', 'hertz'])
+"
+}
+  
+  ## Get task and options ##
+
+TASK=$1 
+shift
+
+if [ ! $TASK ]
+then
+  help
+  exit 0
+fi
+
+case $TASK in
+ -h|--help|help)
+   help
+   exit 0
+  ;; 
+
+  updatetx)
+    if [[ "$1" == "-f" ]] || [[ "$1" == "--file" ]] 
+    then
+      TX_FILE=$2
+      shift
+      shift
+    else     
+      TX_FILE="tx.csv"
+    fi
+    if [ ! -e $TX_FILE ]
+      then 
+        echo "error: '$TX_FILE' doesn't exist" 1>&2
+        exit 1
+    fi
+  ;;
+
+  exporttx) # Export transmitter config file 
+            # from DB and exit. 
+    if [[ "$1" == "-f" ]] || [[ "$1" == "--file" ]] 
+    then
+      TX_FILE=$2
+      shift
+      shift
+    else     
+      TX_FILE="tx.csv"
+    fi
+    export_txlist
+    exit 0
+  ;;
+    
+  status|update|on|off|up|down|start|stop|fetch|cyclerx|do_nothing|die|down_now)
+  ;; 
+    
+  *)
+    echo error: unrecognized task \'$TASK\'
+    exit 1
+  ;;
+
+esac 
+
 
   ## Run task at each site ##
+
+SITELIST=$RMG_SERVER_METADATA_DIR/sitelist.csv
+
+if [ ! -e $SITELIST ]; 
+then
+  echo "error: site configuration information not available (no sitelist.csv)." 1>&2
+  exit 1
+fi 
 
 SITES=$@
 if [[ "$SITES" = "all" ]]
