powerswitch script

diff --git a/serv/rmg b/serv/rmg
--- a/serv/rmg
+++ b/serv/rmg
@@ -75,16 +75,6 @@
 # TODOs 
 # 
 # - 'cyclerx', 'up', 'down'.
-# We now have one network addressible power supply. We will have a file that
-# stores all configuration data for all sites, as well as status bits. For 
-# each site, we'll have a record like (name, comp_ip, power_ip, comp_outlet
-# int, rx_outlet int, powertype, status {"down", "up", "active"}). When this 
-# script starts, it will read the file. When it finishes, it will write it 
-# again. An external script will do Power (powertype, power_ip, action {"ON", 
-# "OFF", "CYCLE"}). Each powertype has its own means of interacting with the 
-# network. For example, for the one Marcel and I worked on, 
-# curl --user admin:1234 "http://192.168.0.100/outlet?1=OFF" 
-# is sufficient. 
 # - Try to read/write sitelist.csv just once. 
 # - Run task on 'all' sites. 
 #
@@ -101,7 +91,9 @@ usage: rmg task [-options] {sites}/all
   on a list of sites. If 'all' is provided, the job will be dispatched to 
   all up sites.   
 
-  'task' is any one of the following: 
+  'task' is any one of the following:
+
+    status       Show status of a site (active/up/down). 
 
     up           Power on remote computer and RMG receiver. If no arguments
                  provided, print sites currently up. 
@@ -123,6 +115,7 @@ usage: rmg task [-options] {sites}/all
     help         Print this. 
 !EOF!
 }
+
 
 ## Configuration and status of sites ##
 touch $RMG_SERVER_SITELIST 2> /dev/null
@@ -151,6 +144,12 @@ function get_sitelist() {
 TASK=$1 
 shift
 
+if [ ! $TASK ]
+then
+  help
+  exit 0
+fi
+
 case $TASK in
  -h|--help|help)
    help
@@ -167,40 +166,46 @@ case $TASK in
       TX_FILE="tx.csv"
     fi
   ;;
+
+  status|up|down|start|stop|fetch|cyclerx)
+  ;; 
+    
+  *)
+    echo error: unrecognized task \'$TASK\'
+    exit 1
+  ;;
+
 esac 
 
-## List of sites to run routine on ##
-SITES=""
-for SITE in $@ 
-do
-  if [[ $SITE =~ [0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3} ]] || [[ $(grep /etc/hosts -e "$SITE") ]] 
-  then
-    [[ ! $SITES =~ $SITE ]] && SITES="$SITES $SITE"
-  else
-    echo error: site \'$SITE\` not recognized.
-    exit 1
-  fi
-done
+
+## Site list ##
+SITES=$@
 
 
 ## Run tasks at each site ##
 count=0
 for SITE in $SITES
 do
-  STATUS=$(get_sitelist $SITE "status")
+
+  STATUS=$(get_sitelist $SITE status)
   if [ $? -ne 0 ]; then 
     echo error: site \'$SITE\' not recognized. 
     exit 1
   fi 
+
   case $TASK in 
+    status)
+      echo "$SITE is $STATUS"
+    ;;
+
     up)
       if [[ $STATUS == "up" ]] || [[ $STATUS == "active" ]]
       then
         echo "$SITE already up!"
       else
         echo "up $SITE"
-        update_sitelist $SITE "status" "up"
-        # TODO power up RMG receiver and computer
+        # TODO
+        update_sitelist $SITE status up
       fi
     ;; 
 
@@ -208,10 +213,10 @@ do
       if [[ $STATUS == "up" ]] || [[ $STATUS == "active" ]]
       then
         echo "down $SITE"
-        update_sitelist $SITE "status" "down"
         ssh -i $RMG_SERVER_SSH_KEYFILE rmg@$SITE "/usr/bin/killall run_rmg 2> /dev/null && /sbin/halt"
-        sleep 5 
-        # TODO power down RMG receiver and computer
+        sleep 5 # wait an appropriate time 
+        # TODO 
+        update_sitelist $SITE status down
       else 
         echo "$SITE already down!"
       fi
@@ -226,6 +231,7 @@ do
         ssh -i $RMG_SERVER_SSH_KEYFILE rmg@$SITE \
             "/usr/local/bin/run_rmg -d $RMG_SITE_DET_DIR -f $RMG_SITE_METADATA_DIR/tx.csv &> \
              $RMG_SITE_METADATA_DIR/run_rmg_$(date -d 'today' +'%Y.%m.%d_%H.%M').txt &"
+        update_sitelist $SITE status active
       elif [[ $STATUS == "active" ]]; then
         echo "$SITE already running"
       else 
@@ -238,51 +244,61 @@ do
       if [[ $STATUS == "active" ]]
       then
         ssh -i $RMG_SERVER_SSH_KEYFILE rmg@$SITE '/usr/bin/killall run_rmg 2> /dev/null'
+        udpate_sitelist $SITE status up
       else 
         echo "$SITE isn't running."
       fi 
     ;;
 
     fetch)
-      echo "fetch $SITE"
-      DIRECTORIES_TO_COPY=$(ssh -i $RMG_SERVER_SSH_KEYFILE rmg@$SITE \ 
-                    "cd $RMG_SITE_DET_DIR && find -type d" | rmg_fetch.py) # directories to copy
-      mkdir -p $RMG_SERVER_DET_DIR/$SITE 
-      ct=0
-      for DIR in $DIRECTORIES_TO_COPY; do
-        echo "copying $DIR"
-        mkdir -p $RMG_SERVER_DET_DIR/$SITE/$DIR
-        rsync -ave "ssh -i $RMG_SERVER_SSH_KEYFILE" rmg@$SITE:$RMG_SITE_DET_DIR/$DIR/* \ 
-          $RMG_SERVER_DET_DIR/$SITE/$DIR                                        # download to RMG server
-        ssh -i $RMG_SERVER_SSH_KEYFILE rmg@$SITE "rm -r $RMG_SITE_DET_DIR/$DIR" # delete from RMG remote
-        let ct=ct+1
-      done
-      if [ $ct -eq 0 ]; then echo "Nothing to fetch."; fi
+      if [[ $STATUS != "down" ]]
+      then
+        echo "fetch $SITE"
+        DIRECTORIES_TO_COPY=$(ssh -i $RMG_SERVER_SSH_KEYFILE rmg@$SITE \ 
+                      "cd $RMG_SITE_DET_DIR && find -type d" | rmg_fetch.py) # directories to copy
+        mkdir -p $RMG_SERVER_DET_DIR/$SITE 
+        ct=0
+        for DIR in $DIRECTORIES_TO_COPY; do
+          echo "copying $DIR"
+          mkdir -p $RMG_SERVER_DET_DIR/$SITE/$DIR
+          rsync -ave "ssh -i $RMG_SERVER_SSH_KEYFILE" rmg@$SITE:$RMG_SITE_DET_DIR/$DIR/* \ 
+            $RMG_SERVER_DET_DIR/$SITE/$DIR                                        # download to RMG server
+          ssh -i $RMG_SERVER_SSH_KEYFILE rmg@$SITE "rm -r $RMG_SITE_DET_DIR/$DIR" # delete from RMG remote
+          let ct=ct+1
+        done
+        if [ $ct -eq 0 ]; then echo "Nothing to fetch."; fi
+      else 
+        echo "$SITE is currently down."
+      fi
     ;;
     
     updatetx) 
-      echo "udpatetx $SITE"
-      if [ -e $TX_FILE ]
+      if [[ $STATUS != "down" ]]
       then
-        scp -i $RMG_SERVER_SSH_KEYFILE $TX_FILE rmg@$SITE:$RMG_SITE_METADATA_DIR/tx.csv 
+        echo "udpatetx $SITE"
+        if [ -e $TX_FILE ]
+        then
+          scp -i $RMG_SERVER_SSH_KEYFILE $TX_FILE rmg@$SITE:$RMG_SITE_METADATA_DIR/tx.csv 
+        else 
+          echo "error: '$TX_FILE' doesn't exist"
+        fi
       else 
-        echo "error: '$TX_FILE' doesn't exist"
+        echo "$STIE is currently down."
       fi
     ;;
-
+ 
     cyclerx)
-      echo "cyclerx $SITE" 
-      # TODO Cycle RMG receiver power. 
+      if [[ $STATUS != "down" ]] 
+      then
+        echo "cyclerx $SITE" 
+        # TODO
+      else 
+        echo "$SITE is currently down."
+      fi
     ;;
     
-    *)
-      echo error: unrecognized task \'$TASK\'
-      exit 1
-    ;;
-
   esac
   let count=count+1
 done
-
 
 
