fix scp error and change function name so as to not confuse with task

diff --git a/serv/rmg b/serv/rmg
--- a/serv/rmg
+++ b/serv/rmg
@@ -146,6 +146,11 @@ case $TASK in
     else     
       TX_FILE="tx.csv"
     fi
+    if [ ! -e $TX_FILE ]
+      then 
+        echo "error: '$TX_FILE' doesn't exist" 1>&2
+        exit 1
+    fi
   ;;
 
   status|update|on|off|up|down|start|stop|fetch|cyclerx|estimate|do_nothing)
@@ -231,7 +236,7 @@ function get_status() {
 
 }
 
-function update() {
+function do_update() {
 # Update a site's state remotely. Copy a new site.csv file 
 # and run rmg-node check. 
   SITE=$1
@@ -273,7 +278,7 @@ do
     update)
       echo "update $SITE"
       if [[ "$ping_computer" == "success" ]]
-        then update $SITE
+        then do_update $SITE
       else 
         echo "error: couldn't update; Computer ping test wasn't successful" 1>&2
       fi
@@ -318,7 +323,7 @@ do
       if [[ "$ping_computer" == "success" ]]
         then 
           rmg_csv $SITE state $TASK < $SITELIST > tmp.csv && mv tmp.csv $SITELIST
-          update $SITE
+          do_update $SITE
         else 
           echo "error: couldn't update; Computer ping test wasn't successful" 1>&2
       fi
@@ -334,7 +339,7 @@ do
               TASK=up
           fi
           rmg_csv $SITE state $TASK < $SITELIST > tmp.csv && mv tmp.csv $SITELIST
-          update $SITE
+          do_update $SITE
           TASK=down
         else
           echo "error: couldn't update; Computer ping test wasn't successful" 1>&2
@@ -346,7 +351,7 @@ do
       if [[ "$ping_computer" == "success" ]]
         then 
           rmg_csv $SITE state active < $SITELIST > tmp.csv && mv tmp.csv $SITELIST
-          update $SITE
+          do_update $SITE
         else 
           echo "error: couldn't update; Computer ping test wasn't successful" 1>&2
       fi
@@ -357,7 +362,7 @@ do
       if [[ "$ping_computer" == "success" ]]
         then
           rmg_csv $SITE state up < $SITELIST > tmp.csv && mv tmp.csv $SITELIST
-          update $SITE
+          do_update $SITE
         else 
           echo "error: couldn't update; Computer ping test wasn't successful" 1>&2
       fi
@@ -391,15 +396,11 @@ do
     
     updatetx) 
       echo "updatetx $SITE"
-      if [ -e $TX_FILE ]
-      then if [[ "$ping_computer" == "success" ]]
+      if [[ "$ping_computer" == "success" ]]
         then
-          scp $SITE:$RMG_SITE_METADATA_DIR/tx.csv 
+          scp $TX_FILE $SITE:$RMG_SITE_METADATA_DIR/tx.csv 
         else
           echo "error: Computer ping test wasn't successful" 1>&2
-        fi
-      else 
-        echo "error: '$TX_FILE' doesn't exist" 1>&2
       fi
     ;;
  
