rmg up/down/start/stop

diff --git a/serv/rmg b/serv/rmg
--- a/serv/rmg
+++ b/serv/rmg
@@ -120,21 +120,6 @@ then
 fi 
 
 
-function update_sitelist () {
-  SITE=$1
-  ENTRY=$2
-  VALUE=$3
-  rmg_csv $SITE $ENTRY $VALUE < $SITELIST > tmp.csv
-  mv tmp.csv $SITELIST
-}
-
-function get_sitelist() {
-  SITE=$1
-  ENTRY=$2
-  rmg_csv $SITE $ENTRY < $SITELIST
-}
-
-
 function status() {
   SITE=$1
 
@@ -180,6 +165,14 @@ function update() {
   ssh -i $RMG_SERVER_SSH_KEYFILE rmg@$ADDR "rmg-node check" 
   rm site.csv
 
+}
+
+function update_sitelist () {
+  SITE=$1
+  ENTRY=$2
+  VALUE=$3
+  rmg_csv $SITE $ENTRY $VALUE < $SITELIST > tmp.csv
+  mv tmp.csv $SITELIST
 }
 
 
@@ -244,10 +237,11 @@ do
       echo "  network: $network_status"
       echo "  site:    $site_status"
       if [[ "$network_status" == "ok" ]] && [[ "$site_status" != "down" ]]
-        then site_goal=`ssh -i $RMG_SERVER_SSH_KEYFILE rmg@$ADDR \
-              "rmg_csv --column state <$RMG_SITE_METADATA_DIR/site.csv"`
-             [[ "$site_goal" != "$GOAL" ]] && \
-              echo "warning: state goal mismatch (serv=$GOAL, node=$site_goal). Suggest update." 1>&2
+        then 
+          site_goal=`ssh -i $RMG_SERVER_SSH_KEYFILE rmg@$ADDR \
+           "rmg_csv --column state <$RMG_SITE_METADATA_DIR/site.csv"`
+          [[ "$site_goal" != "$GOAL" ]] && \
+           echo "warning: goal state mismatch (serv=$GOAL, node=$site_goal). Suggest update." 1>&2
       fi
     ;;
 
@@ -262,18 +256,47 @@ do
 
     up)    # * -> up
       echo "up $SITE"
+      update_sitelist $SITE state up
+      if [[ "$network_status" == "err_comp" ]] || \
+         ( [[ "$network_status" == "ok" ]] && [[ "$site_status" == "down" ]] )
+        then
+          read TYPE IP C_OUTLET <<< $(rmg_csv --row $SITE powertype power_ip comp_outlet <$SITELIST)
+          rmg_powerswitch $TYPE $IP $C_OUTLET CYCLE     
+      elif [[ "$network_status" == "ok" ]] && [[ "$site_status" != "down" ]]
+        then update $SITE $ADDR
+      else 
+        echo "error: couldn't update ($network_status, $site_status)" 1>&2
+      fi
     ;; 
 
     down)  # * -> down
       echo "down $SITE"
+      update_sitelist $SITE state down
+      if [[ "$network_status" == "ok" ]] && [[ "$site_status" != "down" ]]
+        then update $SITE $ADDR
+      else 
+        echo "error: couldn't update ($network_status, $site_status)" 1>&2
+      fi
     ;;
     
     start) # * -> active 
       echo "start $SITE"
+      update_sitelist $SITE state active
+      if [[ "$network_status" == "ok" ]] && [[ "$site_status" != "down" ]]
+        then update $SITE $ADDR
+      else 
+        echo "error: couldn't update ($network_status, $site_status)" 1>&2
+      fi
     ;;
 
     stop)  # active -> up
       echo "stop $SITE"
+      update_sitelist $SITE state up
+      if [[ "$network_status" == "ok" ]] && [[ "$site_status" != "down" ]]
+        then update $SITE $ADDR
+      else 
+        echo "error: couldn't update ($network_status, $site_status)" 1>&2
+      fi
     ;;
 
     fetch)
