changed status function call so it stays in the current shell and the variables are available to the case structure.  Also nil powertypes go to up instead of down

diff --git a/serv/rmg b/serv/rmg
--- a/serv/rmg
+++ b/serv/rmg
@@ -174,22 +174,21 @@ fi
   ## Routines ##
 
 function status() {
-# Probe the the status of a site, return a 3-tuple
-# (site_goal_state, ping_router, ping_computer, site_status).
+# Probe the the status of a site
 
   SITE=$1
 
     #Ping computer
-  read comp_ip power_ip comp_outlet powertype serv_state <<< \
-   $(rmg_csv --row $SITE comp_ip power_ip comp_outlet powertype state <$SITELIST)
+  read comp_ip power_ip comp_outlet rx_outlet powertype serv_state <<< \
+   $(rmg_csv --row $SITE comp_ip power_ip comp_outlet rx_outlet powertype state <$SITELIST)
   ping $comp_ip -c 1 -w 2 &> /dev/null
   if [ $? -eq 0 ]
     then
       ping_computer="success"
-      read goal timestamp site_status <<< `ssh $SITE "rmg_csv --column state <$RMG_SITE_METADATA_DIR/site.csv; rmg_csv --last-row timestamp site_status <$RMG_SITE_METADATA_DIR/status.log"`
+      read site_goal timestamp site_status <<< `ssh $SITE "rmg_csv --column state <$RMG_SITE_METADATA_DIR/site.csv; rmg_csv --last-row timestamp site_status <$RMG_SITE_METADATA_DIR/status.log"`
     else
       ping_computer="failure"
-      goal="unknown"
+      site_goal="unknown"
       site_status="unknown"
       timestamp=`date -u +%s`
   fi
@@ -209,7 +208,7 @@ function status() {
               if [ $? -eq 0 ]
                 then
                   ping_computer="success"
-                  read goal timestamp site_status <<< `ssh $SITE "rmg_csv --column state <$RMG_SITE_METADATA_DIR/site.csv; rmg_csv --last-row timestamp site_status <$RMG_SITE_METADATA_DIR/status.log"`
+                  read site_goal timestamp site_status <<< `ssh $SITE "rmg_csv --column state <$RMG_SITE_METADATA_DIR/site.csv; rmg_csv --last-row timestamp site_status <$RMG_SITE_METADATA_DIR/status.log"`
                 else
                   if [[ $serv_state == "down" ]]
                     then
@@ -230,18 +229,12 @@ function status() {
       power_status=-1
   fi
 
-  echo $goal
-  echo $ping_router
-  echo $ping_computer
-  echo "$site_status, `date --date @$timestamp`"
-
 }
 
 function update() {
 # Update a site's state remotely. Copy a new site.csv file 
 # and run rmg-node check. 
   SITE=$1
-#  ADDR=$2
   rmg_csv --row $SITE <$RMG_SERVER_METADATA_DIR/sitelist.csv | \
   ssh $SITE "cat > site.csv; rmg-node check"  
 
@@ -257,7 +250,7 @@ fi
 count=0
 for SITE in $SITES
 do
-  read site_goal ping_router ping_computer site_status <<< `status $SITE`
+  status $SITE
   read serv_goal ADDR <<< $(rmg_csv --row $SITE state comp_ip <$SITELIST)
   if [ $? -ne 0 ]; then 
     echo "error: site '$SITE' not recognized." 1>&2
@@ -269,7 +262,7 @@ do
       echo "status $SITE"
       echo "  Powerswitch Router Ping Test: $ping_router"
       echo "  Computer Ping Test: $ping_computer"
-      echo "  Site Status:    $site_status"
+      echo "  Site Status:    $site_status, `date --date @$timestamp`"
       if [[ "$ping_computer" == "success" ]]
         then 
           [[ "$site_goal" != "$serv_goal" ]] && \
@@ -291,8 +284,7 @@ do
       if [[ "$ping_router" == "success" ]]
         then if [[ "$site_status" == "off"* ]]  
           then
-            read TYPE IP C_OUTLET <<< $(rmg_csv --row $SITE powertype power_ip comp_outlet <$SITELIST)
-            rmg_powerswitch $TYPE $IP $C_OUTLET ON
+            rmg_powerswitch $powertype $power_ip $comp_outlet ON
           else
             echo "error: first switch the computer's power off." 1>&2
           fi
@@ -309,8 +301,7 @@ do
           then
             if [[ $serv_goal == "down" ]]
             then 
-              read TYPE IP C_OUTLET <<< $(rmg_csv --row $SITE powertype power_ip comp_outlet <$SITELIST)
-              rmg_powerswitch $TYPE $IP $C_OUTLET OFF
+              rmg_powerswitch $powertype $power_ip $comp_outlet OFF
             else
               echo "error: Goal in sitelist.csv is not down; cannot poweroff automatically" 1>&2
             fi
@@ -322,7 +313,7 @@ do
       fi
     ;;
     
-    up|down|do_nothing) # * -> {up, down, do_nothing} 
+    up|do_nothing) # * -> {up, do_nothing} 
       echo "$TASK $SITE"
       if [[ "$ping_computer" == "success" ]]
         then 
@@ -331,6 +322,23 @@ do
         else 
           echo "error: couldn't update; Computer ping test wasn't successful" 1>&2
       fi
+    ;;
+
+    down)
+      echo "down $SITE"
+      if [[ "$ping_computer" == "success" ]]
+        then
+          if [[ "$powertype" == "nil" ]]
+            then
+              echo "Powertype is nil; setting site to up instead of down"
+              TASK=up
+          fi
+          rmg_csv $SITE state $TASK < $SITELIST > tmp.csv && mv tmp.csv $SITELIST
+          update $SITE $ADDR
+          TASK=down
+        else
+          echo "error: couldn't update; Computer ping test wasn't successful" 1>&2
+     fi
     ;;
 
     start) # * -> active 
@@ -399,8 +407,7 @@ do
       echo "cyclerx $SITE"
       if [[ "$ping_router" == "success" ]]
         then
-          read TYPE IP R_OUTLET <<< $(rmg_csv --row $SITE powertype power_ip rx_outlet <$SITELIST)
-          rmg_powerswitch $TYPE $IP $R_OUTLET CYCLE
+          rmg_powerswitch $powertype $poweer_ip $rx_outlet CYCLE
           if [ $? -ne 0 ]
             then echo "error (powerswitch): couldn't connect with host" 1>&2
           fi
