close if statement

diff --git a/serv/rmg b/serv/rmg
--- a/serv/rmg
+++ b/serv/rmg
@@ -352,6 +352,10 @@ do
           do_update $SITE
           rsync -av $SITE:$RMG_SITE_DET_DIR/ $RMG_SERVER_DET_DIR/$SITE/
           ssh $SITE "rmg-node -d 0; rmg-node check"
+        else
+          echo "error: couldn't update; Computer ping test wasn't successful" 1>&2
+     fi
+    ;;
 
     start) # * -> active 
       echo "start $SITE"
