rmg start
Probe RMG to make sure that it will start without trying to start
the signal processsing block.

diff --git a/serv/rmg b/serv/rmg
--- a/serv/rmg
+++ b/serv/rmg
@@ -241,13 +241,24 @@ do
       # timestamped log file. 
       if [[ $STATUS == "up" ]]
       then
-        ssh -i $RMG_SERVER_SSH_KEYFILE rmg@$ADDR \
-            "/usr/local/bin/run_rmg -d $RMG_SITE_DET_DIR \
-             -f $RMG_SITE_METADATA_DIR/tx.csv \
-             -p /dev/ttyUSB0 &> \
-             $RMG_SITE_METADATA_DIR/run_rmg_$(date -d 'today' +'%Y.%m.%d_%H.%M').txt &"
-        # TODO if success, change status
-        update_sitelist $SITE status active
+        # Test if RMG is ready to go. 
+        RES=$(ssh -i $RMG_SERVER_SSH_KEYFILE rmg@$ADDR \
+              "/usr/local/bin/probe_rmg -d $RMG_SITE_DET_DIR \
+               -f $RMG_SITE_METADATA_DIR/tx.csv \
+               -p /dev/ttyUSB0") 
+
+        if [[ $RES =~ "ready" ]]
+          then 
+            ssh -i $RMG_SERVER_SSH_KEYFILE rmg@$ADDR \
+                "/usr/local/bin/run_rmg -d $RMG_SITE_DET_DIR \
+                 -f $RMG_SITE_METADATA_DIR/tx.csv \
+                 -p /dev/ttyUSB0 &> \
+                 $RMG_SITE_METADATA_DIR/run_rmg_$(date -d 'today' +'%Y.%m.%d_%H.%M').txt &"
+            update_sitelist $SITE status active
+          else
+            echo "error: RMG couldn't start." 1>&2
+          fi
+
       elif [[ $STATUS == "active" ]]; then
         echo "$SITE already running"
       else 
@@ -257,15 +268,9 @@ do
 
     stop) 
       echo "stop $SITE"
-      if [[ $STATUS == "active" ]]
-      then
-        ssh -i $RMG_SERVER_SSH_KEYFILE rmg@$ADDR '/usr/bin/killall run_rmg 2> /dev/null'
-
-        # TODO if success, change status
-        update_sitelist $SITE status up
-      else 
-        echo "$SITE isn't running."
-      fi 
+      ssh -i $RMG_SERVER_SSH_KEYFILE rmg@$ADDR '/usr/bin/killall run_rmg 2> /dev/null'
+      # TODO if success, change status
+      update_sitelist $SITE status up
     ;;
 
     fetch)
