starting rmg modifications
Hooks in rmg script for monitoring/controlling the field computers.

diff --git a/serv/rmg b/serv/rmg
--- a/serv/rmg
+++ b/serv/rmg
@@ -28,26 +28,17 @@
 # use an RSA encryption key with no passphrase. The public key is stored 
 # at all RMG remote sites in /home/rmg/.ssh/authorized_keys; the private 
 # key is kept at the server, typically /home/rmg/.ssh/rmg_rsa. This is 
-#because the remotes run the SSH daemon. 
+# because the remotes run the SSH daemon. 
 #
 # Tasks 
 # 
 #  'up/down'
-# 
-# Power the physical hardware on and off. The relevant components are the 
-# RMG receiver and the host computer, called the "RMG remote". The power
-# supply for these will run through a network addressible hub. Theoretically,
-# we should be able to tell this device to turn it sattached components on 
-# and off. 
-#     'up' does nothing special, but 'down' will SIGINT the run_rmg program 
-# if it's running. Next, it sends the RMG remote the halt signal, waits a 
-# sufficient amount of time (say 5 seconds), and powers the computer off. 
-#     A list of up sites is stored in $(pwd)/up_sites. 
+#
+# TODO
 #
 #  'start/stop'
-# 
-# Run and kill the pulse detector module (run_rmg). Output is logged in a 
-# file in the meta data directory.
+#
+# TODO
 #
 #  'fetch' 
 #
@@ -92,8 +83,6 @@ usage: rmg task [-options] {sites}/all
   'task' is any one of the following:
 
     status       Show status of a site. 
-
-    update       Update a site's *goal* state. (TEMP)
 
     up           Power on remote computer and RMG receiver. If no arguments
                  provided, print sites currently up. 
@@ -179,6 +168,11 @@ case $TASK in
 
 esac 
 
+function status () {
+  # TODO 
+  # Return a tuple (net_status,site_status)
+}
+
 
 ## Site list ##
 SITES=$@
@@ -189,7 +183,8 @@ count=0
 for SITE in $SITES
 do
 
-  STATUS=$(get_sitelist $SITE state)
+  GOAL=$(get_sitelist $SITE state)
+
   ADDR=$(get_sitelist $SITE comp_ip)
   if [ $? -ne 0 ]; then 
     echo "error: site '$SITE' not recognized." 1>&2
@@ -198,8 +193,7 @@ do
 
   case $TASK in 
     status)
-      # TODO
-      echo "$SITE is $STATUS"
+      echo "status $SITE"
     ;;
 
     update)
@@ -209,131 +203,55 @@ do
       rm site.csv
     ;;
 
-    up)
-      echo -n "up $SITE "
-      TYPE=$(get_sitelist $SITE powertype) 
-      IP=$(get_sitelist $SITE power_ip)
-      C_OUTLET=$(get_sitelist $SITE comp_outlet)
-      R_OUTLET=$(get_sitelist $SITE rx_outlet)
-      rmg_powerswitch $TYPE $IP $C_OUTLET ON && \
-      rmg_powerswitch $TYPE $IP $R_OUTLET ON
-      if [ $? -ne 0 ]; then
-        echo "error: couldn't reach $ADDR." 1>&2
-        exit 1
-      else
-        echo 
-        update_sitelist $SITE state up
-      fi
+    up)    # * -> down
+      echo "up $SITE"
     ;; 
 
-    down)
-      echo -n "down $SITE "
-      ssh -i $RMG_SERVER_SSH_KEYFILE rmg@$ADDR "/usr/bin/killall run_rmg 2> /dev/null; sudo /sbin/poweroff"
-      sleep 5 # wait an appropriate time
-      TYPE=$(get_sitelist $SITE powertype) 
-      IP=$(get_sitelist $SITE power_ip)
-      C_OUTLET=$(get_sitelist $SITE comp_outlet)
-      R_OUTLET=$(get_sitelist $SITE rx_outlet)
-      rmg_powerswitch $TYPE $IP $C_OUTLET OFF && \
-      rmg_powerswitch $TYPE $IP $R_OUTLET OFF
-      if [ $? -ne 0 ]; then
-        echo "error: couldn't reach $ADDR." 1>&2
-        exit 1
-      else 
-        echo         
-        update_sitelist $SITE state down
-      fi
+    down)  # * -> down
+      echo "down $SITE "
     ;;
     
-    start) 
+    start) # * -> active 
       echo "start $SITE"
-      # Start an RMG process on remote machine. Redirect all output to a 
-      # timestamped log file. 
-      if [[ $STATUS == "up" ]]
-      then
-
-        ssh -i $RMG_SERVER_SSH_KEYFILE rmg@$ADDR \
-            "/usr/local/bin/run_rmg -d $RMG_SITE_DET_DIR \
-             -f $RMG_SITE_METADATA_DIR/tx.csv \
-             -p /dev/ttyUSB0 > \
-             $RMG_SITE_METADATA_DIR/run_rmg_$(date -d 'today' +'%Y.%m.%d_%H.%M').txt \
-             2> $RMG_SITE_METADATA_DIR/run_rmg_error.txt &"
-
-        sleep 5
-
-        if [ $(ssh -i $RMG_SERVER_SSH_KEYFILE rmg@$ADDR "pgrep run_rmg") ]
-          then 
-            update_sitelist $SITE state active
-          else
-            echo "error: RMG couldn't start." 1>&2
-            echo "----------------------------------------" 1>&2
-            ssh -i $RMG_SERVER_SSH_KEYFILE rmg@$ADDR "cat $RMG_SITE_METADATA_DIR/run_rmg_error.txt" 1>&2
-            echo "----------------------------------------" 1>&2
-          fi
-
-      elif [[ $STATUS == "active" ]]; then
-        echo "$SITE already running"
-
-      else 
-        echo "$SITE is currently down."
-      fi 
     ;;
 
-    stop) 
+    stop)  # active -> up
       echo "stop $SITE"
-      ssh -i $RMG_SERVER_SSH_KEYFILE rmg@$ADDR '/usr/bin/killall run_rmg 2> /dev/null'
-      # TODO if success, change status
-      update_sitelist $SITE state up
     ;;
 
     fetch)
-      if [[ $STATUS != "down" ]]
-      then
-        echo "fetch $SITE"
-        DIRECTORIES_TO_COPY=$(ssh -i $RMG_SERVER_SSH_KEYFILE rmg@$ADDR "cd $RMG_SITE_DET_DIR \
-          && find -type d" | rmg_fetch) # directories to copy
-        mkdir -p $RMG_SERVER_DET_DIR/$SITE 
-        ct=0
-        for DIR in $DIRECTORIES_TO_COPY; do
-          echo "copying $DIR"
-          mkdir -p $RMG_SERVER_DET_DIR/$SITE/$DIR
-          rsync -ave "ssh -i $RMG_SERVER_SSH_KEYFILE" rmg@$ADDR:$RMG_SITE_DET_DIR/$DIR/* \
-            $RMG_SERVER_DET_DIR/$SITE/$DIR                                        # download to RMG server
-          ssh -i $RMG_SERVER_SSH_KEYFILE rmg@$ADDR "rm -r $RMG_SITE_DET_DIR/$DIR" # delete from RMG remote
-          let ct=ct+1
-        done
-        if [ $ct -eq 0 ]; then echo "Nothing to fetch."; fi
-      else 
-        echo "$SITE is currently down."
-      fi
+      echo "fetch $SITE"
+      DIRECTORIES_TO_COPY=$(ssh -i $RMG_SERVER_SSH_KEYFILE rmg@$ADDR "cd $RMG_SITE_DET_DIR \
+        && find -type d" | rmg_fetch) # directories to copy
+      mkdir -p $RMG_SERVER_DET_DIR/$SITE 
+      ct=0
+      for DIR in $DIRECTORIES_TO_COPY; do
+        echo "copying $DIR"
+        mkdir -p $RMG_SERVER_DET_DIR/$SITE/$DIR
+        rsync -ave "ssh -i $RMG_SERVER_SSH_KEYFILE" rmg@$ADDR:$RMG_SITE_DET_DIR/$DIR/* \
+          $RMG_SERVER_DET_DIR/$SITE/$DIR                                        # download to RMG server
+        ssh -i $RMG_SERVER_SSH_KEYFILE rmg@$ADDR "rm -r $RMG_SITE_DET_DIR/$DIR" # delete from RMG remote
+        let ct=ct+1
+      done
+      if [ $ct -eq 0 ]; then echo "Nothing to fetch."; fi
     ;;
     
     updatetx) 
-      if [[ $STATUS != "down" ]]
+      echo "udpatetx $SITE"
+      if [ -e $TX_FILE ]
       then
-        echo "udpatetx $SITE"
-        if [ -e $TX_FILE ]
-        then
-          scp -i $RMG_SERVER_SSH_KEYFILE $TX_FILE rmg@$ADDR:$RMG_SITE_METADATA_DIR/tx.csv 
-        else 
-          echo "error: '$TX_FILE' doesn't exist" 1>&2
-        fi
+        scp -i $RMG_SERVER_SSH_KEYFILE $TX_FILE rmg@$ADDR:$RMG_SITE_METADATA_DIR/tx.csv 
       else 
-        echo "$STIE is currently down."
+        echo "error: '$TX_FILE' doesn't exist" 1>&2
       fi
     ;;
  
     cyclerx)
-      if [[ $STATUS != "down" ]] 
-      then
-        echo "cyclerx $SITE" 
-        TYPE=$(get_sitelist $SITE powertype) 
-        IP=$(get_sitelist $SITE power_ip)
-        R_OUTLET=$(get_sitelist $SITE rx_outlet)
-        rmg_powerswitch $TYPE $IP $R_OUTLET CYCLE
-      else 
-        echo "$SITE is currently down."
-      fi
+      echo "cyclerx $SITE" 
+      TYPE=$(get_sitelist $SITE powertype) 
+      IP=$(get_sitelist $SITE power_ip)
+      R_OUTLET=$(get_sitelist $SITE rx_outlet)
+      rmg_powerswitch $TYPE $IP $R_OUTLET CYCLE
     ;;
     
     estimate)
