changed rmg script to report results of ping test individually, removed the identityfile for ssh, changed rmg-node status_logging so check doesn't log if nothing occurs

diff --git a/serv/rmg b/serv/rmg
--- a/serv/rmg
+++ b/serv/rmg
@@ -32,13 +32,21 @@
 #
 # Tasks 
 # 
-#  'up/down'
+#  'up'
 #
-# TODO
+#  set site computer's goal to up: computer on, receiver off
 #
-#  'start/stop'
+#  'down'
 #
-# TODO
+#  set site computer's goal to down: receiver off, computer to shutdown in 300 seconds
+#
+#  'start'
+#
+#  set site computer's goal to active: computer on, receiver on,
+#
+#  'stop'
+#
+#  same as 'up'
 #
 #  'fetch' 
 #
@@ -96,7 +104,7 @@ usage: rmg task [-options] {sites}/all
                  Store pulse data remotely. (Transition to active state.)
 
     stop         Power off the RMG receiver and stop the software defined 
-                 radio. (Trnasition to up staqte.)
+                 radio. (Transition to up state.)
 
     fetch        Download pulse data from site to server. Delete downloaded 
                  data from remote machine. 
@@ -167,59 +175,65 @@ fi
 
 function status() {
 # Probe the the status of a site, return a 3-tuple
-# (site_goal_state, net_status, site_status).
+# (site_goal_state, ping_router, ping_computer, site_status).
 
   SITE=$1
+
+    #Ping computer
   read comp_ip power_ip comp_outlet powertype <<< \
    $(rmg_csv --row $SITE comp_ip power_ip comp_outlet powertype <$SITELIST)
   ping $comp_ip -c 1 -w 2 &> /dev/null
-  if [ $? -eq 0 ]; then
-    read goal timestamp site_status <<< `ssh -i $RMG_SERVER_SSH_KEYFILE rmg@$comp_ip "rmg_csv --column state <$RMG_SITE_METADATA_DIR/site.csv; rmg_csv --last-row timestamp site_status <$RMG_SITE_METADATA_DIR/status.log"`
-    echo $goal
-    echo ok
-    echo "$site_status, `date --date @$timestamp`"
-  else
-    ping $power_ip -c 1 -w 2 &> /dev/null
-    if [ $? -eq 0 ]; then
-      
-      power_status=$(rmg_powerswitch $powertype $power_ip $comp_outlet QUERY)
-      if [ $power_status -eq 1 ]; then
-
-        ping $comp_ip -c 1 -w 2 &> /dev/null
-        if [ $? -eq 0 ]; then
-          read goal timestamp site_status <<< `ssh -i $RMG_SERVER_SSH_KEYFILE rmg@$comp_ip "rmg_csv --column state <$RMG_SITE_METADATA_DIR/site.csv; rmg_csv --last-row timestamp site_status <$RMG_SITE_METADATA_DIR/status.log"`
-          echo $goal
-          echo ok
-          echo $site_status, `date --date @$timestamp`
-          
-          
-        else 
-          echo unknown
-          echo err_comp
-          echo unknown
-        fi      
-
-      else 
-        echo unknown
-        echo ok
-        echo down
-      fi    
-
+  if [ $? -eq 0 ]
+    then
+      ping_computer="success"
+      read goal timestamp site_status <<< `ssh $SITE "rmg_csv --column state <$RMG_SITE_METADATA_DIR/site.csv; rmg_csv --last-row timestamp site_status <$RMG_SITE_METADATA_DIR/status.log"`
     else
-      echo unknown
-      echo err_pwr
-      echo unknown
-    fi
+      ping_computer="failure"
+      goal="unknown"
+      site_status="unknown"
+      timestamp=`date -u +%s`
   fi
+
+    #Ping router
+  ping $power_ip -c 1 -w 2 &> /dev/null
+  if [ $? -eq 0 ]
+    then
+      ping_router="success"
+      power_status=$(rmg_powerswitch $powertype $power_ip $comp_outlet QUERY)
+      if [[ $ping_computer == "failure" ]]  && [ $power_status -eq 1 ]
+        then
+            #Try pinging computer again
+          ping $comp_ip -c 1 -w 2 &> /dev/null
+          if [ $? -eq 0 ]
+            then
+              ping_computer="success"
+              read goal timestamp site_status <<< `ssh $SITE "rmg_csv --column state <$RMG_SITE_METADATA_DIR/site.csv; rmg_csv --last-row timestamp site_status <$RMG_SITE_METADATA_DIR/status.log"`
+          fi
+        else
+          if [ $power_status -eq 0 ]
+            then
+              site_status="off"
+          fi
+      fi
+    else
+      ping_router="failure"
+      power_status=-1
+  fi
+
+  echo $goal
+  echo $ping_router
+  echo $ping_computer
+  echo "$site_status, `date --date @$timestamp`"
+
 }
 
 function update() {
 # Update a site's state remotely. Copy a new site.csv file 
 # and run rmg-node check. 
   SITE=$1
-  ADDR=$2
+#  ADDR=$2
   rmg_csv --row $SITE <$RMG_SERVER_METADATA_DIR/sitelist.csv | \
-  ssh -i $RMG_SERVER_SSH_KEYFILE rmg@$ADDR "cat > site.csv; rmg-node check"  
+  ssh $SITE "cat > site.csv; rmg-node check"  
 
 }
 
@@ -230,7 +244,7 @@ SITES=$@
 count=0
 for SITE in $SITES
 do
-  read site_goal network_status site_status <<< `status $SITE`
+  read site_goal ping_router ping_computer site_status <<< `status $SITE`
   read serv_goal ADDR <<< $(rmg_csv --row $SITE state comp_ip <$SITELIST)
   if [ $? -ne 0 ]; then 
     echo "error: site '$SITE' not recognized." 1>&2
@@ -240,9 +254,10 @@ do
   case $TASK in 
     status)
       echo "status $SITE"
-      echo "  network: $network_status"
-      echo "  site:    $site_status"
-      if [[ "$network_status" == "ok" ]] && [[ "$site_status" != "down" ]]
+      echo "  Powerswitch Router Ping Test: $ping_router"
+      echo "  Computer Ping Test: $ping_computer"
+      echo "  Site Status:    $site_status"
+      if [[ "$ping_computer" == "success" ]]
         then 
           [[ "$site_goal" != "$serv_goal" ]] && \
            echo "warning: goal state mismatch (serv=$serv_goal, node=$site_goal). Suggest update." 1>&2
@@ -251,99 +266,127 @@ do
 
     update)
       echo "update $SITE"
-      if [[ "$network_status" == "ok" ]] && [[ "$site_status" != "down" ]]
+      if [[ "$ping_computer" == "success" ]]
         then update $SITE $ADDR
       else 
-        echo "error: couldn't update ($network_status, $site_status)" 1>&2
+        echo "error: couldn't update; Computer ping test wasn't successful" 1>&2
       fi
     ;;
 
     on)
       echo "on $SITE"
-      if [[ "$network_status" == "ok" ]] && [[ "$site_status" == "down" ]]  
-        then read TYPE IP C_OUTLET <<< $(rmg_csv --row $SITE powertype power_ip comp_outlet <$SITELIST)
-             rmg_powerswitch $TYPE $IP $C_OUTLET ON
-      else
-        echo "error: first switch the computer's power off." 1>&2
+      if [[ "$ping_router" == "success" ]]
+        then if [[ "$site_status" == "off" ]]  
+          then
+            read TYPE IP C_OUTLET <<< $(rmg_csv --row $SITE powertype power_ip comp_outlet <$SITELIST)
+            rmg_powerswitch $TYPE $IP $C_OUTLET ON
+          else
+            echo "error: first switch the computer's power off." 1>&2
+        else
+          echo "error: Router ping test wasn't sucessful" 1>&2
       fi
     ;;
 
     off)
       echo "off $SITE"
-      if [[ "$network_status" == "err_comp" ]]
-        then read TYPE IP C_OUTLET <<< $(rmg_csv --row $SITE powertype power_ip comp_outlet <$SITELIST)
-             rmg_powerswitch $TYPE $IP $C_OUTLET OFF
+      if [[ "$ping_router" == "success" ]]
+        then if [[ "$ping_computer" == "failure" ]]
+          then if [[ $serv_goal == "down" ]]
+            then 
+              read TYPE IP C_OUTLET <<< $(rmg_csv --row $SITE powertype power_ip comp_outlet <$SITELIST)
+              rmg_powerswitch $TYPE $IP $C_OUTLET OFF
+            else
+              echo "error: Goal in sitelist.csv is not down; cannot poweroff automatically" 1>&2
+          else
+            echo "error: Computer is responding to ping; please shutdown computer" 1>&2
         else 
-          echo "error: first shutdown the computer."
+          echo "error: Router ping test wasn't sucessful" 1>&2
         fi
     ;;
     
     up|down|do_nothing) # * -> {up, down, do_nothing} 
       echo "$TASK $SITE"
-      if [[ "$network_status" == "ok" ]] && [[ "$site_status" != "down" ]]
+      if [[ "$network_status" == "success" ]]
         then 
           rmg_csv $SITE state $TASK < $SITELIST > tmp.csv && mv tmp.csv $SITELIST
           update $SITE $ADDR
-      else 
-        echo "error: couldn't update ($network_status, $site_status)" 1>&2
-      fi
-    ;; 
-
-    start) # * -> active 
-      echo "start $SITE"
-      if [[ "$network_status" == "ok" ]] && [[ "$site_status" != "down" ]]
-        then rmg_csv $SITE state active < $SITELIST > tmp.csv && mv tmp.csv $SITELIST
-             update $SITE $ADDR
-      else 
-        echo "error: couldn't update ($network_status, $site_status)" 1>&2
+        else 
+          echo "error: couldn't update; Computer ping test wasn't successful" 1>&2
       fi
     ;;
 
-    stop)  # active -> up
+    start) # * -> active 
+      echo "start $SITE"
+      if [[ "$ping_computer" == "success" ]]
+        then 
+          rmg_csv $SITE state active < $SITELIST > tmp.csv && mv tmp.csv $SITELIST
+          update $SITE $ADDR
+        else 
+          echo "error: couldn't update; Computer ping test wasn't successful" 1>&2
+      fi
+    ;;
+
+    stop)  # * -> up
       echo "stop $SITE"
-      if [[ "$network_status" == "ok" ]] && [[ "$site_status" != "down" ]]
-        then rmg_csv $SITE state up < $SITELIST > tmp.csv && mv tmp.csv $SITELIST
-             update $SITE $ADDR
-      else 
-        echo "error: couldn't update ($network_status, $site_status)" 1>&2
+      if [[ "$ping_computer" == "success" ]]
+        then
+          rmg_csv $SITE state up < $SITELIST > tmp.csv && mv tmp.csv $SITELIST
+          update $SITE $ADDR
+        else 
+          echo "error: couldn't update; Computer ping test wasn't successful" 1>&2
       fi
     ;;
 
     fetch)
       echo "fetch $SITE"
-      DIRECTORIES_TO_COPY=$(ssh -i $RMG_SERVER_SSH_KEYFILE rmg@$ADDR "cd $RMG_SITE_DET_DIR \
-        && find -type d" | rmg_fetch) # directories to copy
-      mkdir -p $RMG_SERVER_DET_DIR/$SITE 
-      ct=0
-      for DIR in $DIRECTORIES_TO_COPY; do
-        echo "copying $DIR"
-        mkdir -p $RMG_SERVER_DET_DIR/$SITE/$DIR
-        rsync -ave "ssh -i $RMG_SERVER_SSH_KEYFILE" rmg@$ADDR:$RMG_SITE_DET_DIR/$DIR/* \
-          $RMG_SERVER_DET_DIR/$SITE/$DIR                                          # download to RMG server
-        if [ $? -eq 0 ]; then
-          ssh -i $RMG_SERVER_SSH_KEYFILE rmg@$ADDR "rm -r $RMG_SITE_DET_DIR/$DIR" # delete from RMG remote
-        fi
-        let ct=ct+1
-      done
-      if [ $ct -eq 0 ]; then echo "Nothing to fetch."; fi
+      if [[ "$ping_computer" == "success" ]]
+        then
+          DIRECTORIES_TO_COPY=$(ssh $SITE "cd $RMG_SITE_DET_DIR \
+            && find -type d" | rmg_fetch) # directories to copy
+          mkdir -p $RMG_SERVER_DET_DIR/$SITE 
+          ct=0
+          for DIR in $DIRECTORIES_TO_COPY; do
+            echo "copying $DIR"
+            mkdir -p $RMG_SERVER_DET_DIR/$SITE/$DIR
+              # download to RMG server
+            rsync -av $SITE:$RMG_SITE_DET_DIR/$DIR/* \
+              $RMG_SERVER_DET_DIR/$SITE/$DIR
+            if [ $? -eq 0 ]; then
+                # delete from RMG remote
+              ssh $SITE "rm -r $RMG_SITE_DET_DIR/$DIR" 
+            fi
+            let ct=ct+1
+          done
+          if [ $ct -eq 0 ]; then echo "Nothing to fetch."; fi
+        else
+          echo "error: Computer ping test wasn't successful" 1>&2
+      fi
     ;;
     
     updatetx) 
       echo "updatetx $SITE"
       if [ -e $TX_FILE ]
-      then
-        scp -i $RMG_SERVER_SSH_KEYFILE $TX_FILE rmg@$ADDR:$RMG_SITE_METADATA_DIR/tx.csv 
+      then if [[ "$ping_computer" == "success" ]]
+        then
+          scp $SITE:$RMG_SITE_METADATA_DIR/tx.csv 
+        else
+          echo "error: Computer ping test wasn't successful" 1>&2
       else 
         echo "error: '$TX_FILE' doesn't exist" 1>&2
       fi
     ;;
  
     cyclerx)
-      echo "cyclerx $SITE" 
-      read TYPE IP R_OUTLET <<< $(rmg_csv --row $SITE powertype power_ip rx_outlet <$SITELIST)
-      rmg_powerswitch $TYPE $IP $R_OUTLET CYCLE
-      if [ $? -ne 0 ]
-        then echo "error (powerswitch): couldn't connect with host" 1>&2
+      echo "cyclerx $SITE"
+      if [[ "$ping_router" == "success" ]]
+        then
+          read TYPE IP R_OUTLET <<< $(rmg_csv --row $SITE powertype power_ip rx_outlet <$SITELIST)
+          rmg_powerswitch $TYPE $IP $R_OUTLET CYCLE
+          if [ $? -ne 0 ]
+            then echo "error (powerswitch): couldn't connect with host" 1>&2
+          fi
+        else
+          echo "error: Router ping test wasn't successful" 1>&2
       fi
     ;;
     
