State transitions are working. The next thing is to run this as a service, then have rmg-serv update state remotely.
Signed-off-by: Chris <cjpatton@ucdavis.edu>

diff --git a/node/rmg-node b/node/rmg-node
--- a/node/rmg-node
+++ b/node/rmg-node
@@ -1,12 +1,6 @@
 #!/bin/bash
 # rmg-node
-# This script is part of the QRAAT system. Control the state of the 
-# field computer locally. This provides functionality to transition
-# the state immediately, but also could be used as a service to do 
-# system monitoring. 'rmg-node check' checks the goal state specified 
-# in the local configuration file, e.g. /home/rmg/site.csv, and 
-# coerces that state. For example, every minute in crontab: 
-# * * * * * /usr/local/bin/rmg-node check
+# This script is part of the QRAAT system.
 #
 # Copyright (C) 2013 Christopher Patton
 # 
@@ -23,15 +17,16 @@
 # You should have received a copy of the GNU General Public License
 # along with this program.  If not, see <http://www.gnu.org/licenses/>.
 
+source rmg_env  # setup RMG environment variables
+
 function help() {
   cat <<!EOF!
-usage: rmg-node state/check/help [-options]
+usage: rmg-node state/help [-options]
 
   This program is part of the QRAAT system. It controls the field site 
   by transitioning the computer to the specified state.  
 
-  Change the state immediately if a state is given. 'state' is any one 
-  of the following:
+  'state' is any one of the following:
 
     active       Computer is powered, RMG receiver is on, and the pulse 
                  detector is running. 
@@ -43,37 +38,12 @@ usage: rmg-node state/check/help [-options]
                  there is a timer set to shutdown. If such a timer exists
                  and delay is specified, it is reset to M minutes. If one 
                  doesn't exist, an M-minute timer is created (5 minutes 
-                 if unspecified.) 
-
-  'check' verifies that the system is in the state specified by site 
-  configuration file, usually /home/rmg/site.csv. If not, it immediately 
-  performs the transition.
+                 if unspecified.)  
 
   'help' prints this help. 
 !EOF!
 }
 
-## Site configuration ##
-source rmg_env                # setup RMG environment variables
-SITE=$RMG_SITE_METADATA_DIR/site.csv
-STATUS_LOG=$RMG_SITE_METADATA_DIR/status.log
-
-if [ ! -e $SITE ]
-then
-  echo "error: site configuration information not available (no site.csv)." 1>&2
-  exit 1
-fi 
-
-if [ ! -e $STATUS_LOG ]
-then
-  echo "timestamp,site_status" | cat >> $STATUS_LOG
-fi
-
-if [ ! $RETRY_MAX ]
-then
-  echo "warning: setting max retry count to 10." 1>&2
-  export RETRY_MAX=10
-fi 
 
 ## Get goal state and options ##
 GOAL=$1 
@@ -103,11 +73,6 @@ case $GOAL in
       DELAY=5
     fi
   ;;
-
-  check) 
-    GOAL=$(rmg_sitelist --column state <$SITE)
-    DELAY=5
-  ;;
   
   *)
     echo error: unrecognized state \'$GOAL\'
@@ -116,13 +81,36 @@ case $GOAL in
 
 esac 
 
+
+## Site configuration ##
+SITE=$RMG_SITE_METADATA_DIR/site.csv
+STATUS_LOG=$RMG_SITE_METADATA_DIR/status.log
+if [ ! -e $SITE ]
+then
+  echo "error: site configuration information not available (no site.csv)." 1>&2
+  exit 1
+fi 
+
+if [ ! -e $STATUS_LOG ]
+then
+  echo "timestamp,site_status" | cat >> $STATUS_LOG
+fi
+
+if [ ! $RETRY_CT ] || [ ! $RETRY_MAX ]
+then
+  echo "warning: setting retry count to zero." 1>&2
+  RETRY_CT=0
+  RETRY_MAX=10
+fi 
+
+
 ## Collect status information ##
 TYPE=$(rmg_sitelist --column powertype <$SITE)
 IP=$(rmg_sitelist --column power_ip <$SITE)
 RX_OUTLET=$(rmg_sitelist --column rx_outlet <$SITE)
 
 RX_STATE=$(rmg_powerswitch $TYPE $IP $RX_OUTLET QUERY)
-SDR_PID=$(pgrep rmg_runretry)
+SDR_PID=$(pgrep run_rmg)
 
 PREV_STATUS=$(rmg_sitelist --column site_status <$STATUS_LOG | tail -1)
 PREV_TIME=$(rmg_sitelist --column timestamp <$STATUS_LOG | tail -1)
@@ -137,8 +125,7 @@ function up() {
       if [ $RX_STATE -ne 0 ]                   # RMG receiver off
         then rmg_powerswitch $TYPE $IP $RX_OUTLET OFF; fi 
       if [ $SDR_PID ]                          # Pulse detector stopped
-        then kill -SIGTERM $SDR_PID `pgrep run_rmg`; fi 
-
+        then kill -s INT $SDR_PID; fi
       echo up
   fi
 }
@@ -151,27 +138,44 @@ function down() {
       if [ $RX_STATE -ne 0 ]                   # RMG receiver off
         then rmg_powerswitch $TYPE $IP $RX_OUTLET OFF; fi 
       if [ $SDR_PID ]                          # Pulse detector stopped
-        then kill -SIGTERM $SDR_PID `pgrep run_rmg`; fi 
+        then kill -s INT $SDR_PID; fi
       echo down\($(($DELAY * 60))\)
   fi
 }
 
 function active() {
-   
-  if [ $RX_STATE -eq 1 ] && [ $SDR_PID ]
+  if [ $RETRY_CT -gt $RETRY_MAX ]
     then 
-      echo "running" 1>&2
-  else
-      nohup rmg_runretry $TYPE $IP $RX_OUTLET &> /dev/null < /dev/null & 
+      if [ $RX_STATE -ne 0 ]                   # RMG receiver off
+       then rmg_powerswitch $TYPE $IP $RX_OUTLET OFF; fi 
+      if [ $SDR_PID ]                          # Pulse detector stopped
+        then kill -s INT $SDR_PID; fi
+      echo err_fatal
+   
+  elif [ $RX_STATE -eq 1 ] && [ $SDR_PID ]
+    then
+      let RETRY_CT=0
+      echo active
+  
+  else 
+      if [ $RX_STATE -ne 1 ]                   # RMG receiver on
+       then rmg_powerswitch $TYPE $IP $RX_OUTLET ON; fi 
+      if [ ! $SDR_PID ]                        # Pulse detector running
+        then 
+          run_rmg -d $RMG_SITE_DET_DIR \
+                  -f $RMG_SITE_METADATA_DIR/tx.csv \
+                  -p /dev/ttyUSB0 \
+                  1> $RMG_SITE_METADATA_DIR/run_rmg$(date -d 'today' +'%Y.%m.%d_%H.%M').txt \
+                  2> $RMG_SITE_METADATA_DIR/run_rmg_error.txt &
+      fi
+      let RETRY_CT=RETRY_CT+1
+      echo err_retry\($RETRY_CT\)
   fi
-
-  echo active
 }
 
 
 ## Execute state transition ##
 case $GOAL in
-
   active)
     STATUS=`active`
   ;; 
@@ -188,11 +192,7 @@ esac
 
 
 ## Log new state, shutdown if time has elapsed ## 
-
 TIME=`date -u +%s`
-# Timestamp is in seconds after epoch. This makes it easier to 
-# calculate the time-elapse. To print the timestamp pretty, do:
-# date --date @`rmg_sitelist -c timestamp <status.log | tail -1` 
 case $STATUS in
   
   down\(*\))
@@ -208,8 +208,7 @@ case $STATUS in
     if [ ! $DELAY_SPECIFIED ] && [ $D ] && [ $PREV_TIME ] && [ $(($TIME - $PREV_TIME)) -gt $D ]
       then
         echo "$TIME,shutdown" | cat >> $STATUS_LOG
-        echo "time to shutdown!" 
-        #sudo poweroff FIXME
+        echo "time to shutdown!" # TODO
 
     ## reset timer or set a new one ##
     elif [ $DELAY_SPECIFIED ] || [ ! $D ]
